#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1522170476                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : #assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Vélibz                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Gratuit                                         # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Vélibz est une app qui facilite vos déplacements à Vélib !

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexandre Guibert                               
your_link                                 : https://www.linkedin.com/in/alexandre-guibert-896a2b17/                     
your_city                                 : Paris                                
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Carte
    description                           : Retrouvez les stations et la disponibilité en vélos mécaniques, électriques ou parkings sur la carte.
    fontawesome_icon_name                 : compass
    
  - title                                 : Recherche
    description                           : Recherchez une adresse et trouvez les stations à proximité.
    fontawesome_icon_name                 : search

  - title                                 : Itinéraire
    description                           : Démarrez un itinéraire vers une station simplement en la sélectionnant.
    fontawesome_icon_name                 : directions

  - title                                 : Widget
    description                           : Retrouvez sur l'écran verrouillé les stations les plus proches de vous avec leurs disponibilités, et choisissez en une pour démarrer un itinéraire vélo.
    fontawesome_icon_name                 : bicycle


# Theme Settings
topbar_color                              : "#0D101B"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#000000"

link_color                                : "#0095FF"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#fff"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#79C618"
feature_icons_background_color            : "#333"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
